### ISSUE TITLE
Why not merge this into Emacs?

### ISSUE THREAD

**Issue by rhaps0dy** [doublep/iter2#1] opened 2022-01-30 18:12 UTC
Since your work is a faster, fully compatible version of `generator.el`, wouldn't it be a good idea to just replace `generator` by `iter2`? This way everyone benefits from it, and we don't have to duplicate packages which already rely on `generator.el`.

(I understand if you just say "It's too much work to interact with the Emacs mailing list", seems reasonable!)

**Comment by doublep** [comment] 2022-01-30 18:36
I have very bad experience negotiating anything with Emacs devel team. If you are willing to do this, I don't mind (I even submitted necessary paperworks long time ago). But I'm not going to do anything myself. Closing as not a bug, but feel free to take or not to take any further steps on your own.

**Closed as completed by doublep** 2022-01-30 18:36 UTC

**Comment by rhaps0dy** [comment] 2022-01-30 18:41
Thank you for your prompt reply! This is exactly what I wanted to know. I might well go ahead and do the negotiation myself.

I have no experience negotiating with the Emacs team, but I recently read somewhere that we should consider adding our hacks to the Emacs tree more often. Alas, I cannot find the reference now;  I'll post it when I do it.
